// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'cart_response.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

CartDataReponse _$CartDataReponseFromJson(Map<String, dynamic> json) =>
    CartDataReponse(
      data: json['data'] == null
          ? null
          : DataCardResponse.fromJson(json['data'] as Map<String, dynamic>),
    );

Map<String, dynamic> _$CartDataReponseToJson(CartDataReponse instance) =>
    <String, dynamic>{
      'data': instance.data,
    };

DataCardResponse _$DataCardResponseFromJson(Map<String, dynamic> json) =>
    DataCardResponse(
      id: json['id'] as int?,
      userId: json['user_id'] as int?,
      sessionId: json['session_id'] as String?,
      phone: json['phone'] as String?,
      address: json['address'] as String?,
      shipAddressLatlong: json['ship_address_latlong'] as String?,
      shippingAddressId: json['shipping_address_id'] as String?,
      addressWindowId: json['address_window_id'] as String?,
      streetAddress: json['street_address'] as String?,
      shippingAddressFullName: json['shipping_address_full_name'] as String?,
      shippingAddressWard: json['shipping_address_ward'] as String?,
      shippingAddressDistrict: json['shipping_address_district'] as String?,
      shippingAddressCity: json['shipping_address_city'] as String?,
      description: json['description'] as String?,
      paymentMethod: json['payment_method'] as String?,
      paymentMethodName: json['payment_method_name'] as String?,
      shippingMethod: json['shipping_method'] as String?,
      shippingMethodCode: json['shipping_method_code'] as String?,
      shippingMethodName: json['shipping_method_name'] as String?,
      shippingService: json['shipping_service'] as String?,
      isFreeship: json['is_freeship'] as int?,
      shippingNote: json['shipping_note'] as String?,
      shippingDiff: json['shipping_diff'] as String?,
      serviceName: json['service_name'] as String?,
      extraService: json['extra_service'] as String?,
      shipFee: json['ship_fee'] as String?,
      shipFeeDown: json['ship_fee_down'] as String?,
      estimatedDeliverTime: json['estimated_deliver_time'] as String?,
      ladingMethod: json['lading_method'] as String?,
      shipFeeStart: json['ship_fee_start'] as String?,
      receivingTime: json['receiving_time'] as String?,
      total: json['total'] as int?,
      customerPoint: json['customer_point'] as int?,
      customerExchangePoint: json['customer_exchange_point'] as String?,
      totalProductPromotion: json['total_product_promotion'] as int?,
      totalProduct: json['total_product'] as int?,
      totalProductPromotionFortmated:
          json['total_product_promotion_fortmated'] as String?,
      totalProductFortmated: json['total_product_fortmated'] as String?,
      totalFortmated: json['total_fortmated'] as String?,
      totalQuantity: json['total_quantity'] as int?,
      createdAt: json['created_at'] as String?,
      createdBy: json['created_by'] as String?,
      updatedAt: json['updated_at'] as String?,
      updatedBy: json['updated_by'] as String?,
      details: (json['details'] as List<dynamic>?)
          ?.map((e) => Details.fromJson(e as Map<String, dynamic>))
          .toList(),
      totalPoint: json['total_point'] as String?,
      fullName: json['full_name'] as String?,
      email: json['email'] as String?,
      distributorId: json['distributor_id'] as int?,
      distributorCode: json['distributor_code'] as String?,
      distributorName: json['distributor_name'] as String?,
      distributorPhone: json['distributor_phone'] as String?,
      distributorLat: json['distributor_lat'] as String?,
      distributorLong: json['distributor_long'] as String?,
      distributorPostcode: json['distributor_postcode'] as String?,
      orderType: json['order_type'] as String?,
      distributorCityCode: json['distributor_city_code'] as String?,
      distributorDistrictCode: json['distributor_district_code'] as String?,
      distributorWardCode: json['distributor_ward_code'] as String?,
      distributorCityName: json['distributor_city_name'] as String?,
      distributorDistrictName: json['distributor_district_name'] as String?,
      distributorWardName: json['distributor_ward_name'] as String?,
      distributorFullAddress: json['distributor_full_address'] as String?,
      customerCityCode: json['customer_city_code'] as String?,
      customerDistrictCode: json['customer_district_code'] as String?,
      customerWardCode: json['customer_ward_code'] as String?,
      customerCityName: json['customer_city_name'] as String?,
      customerDistrictName: json['customer_district_name'] as String?,
      customerWardName: json['customer_ward_name'] as String?,
      customerFullAddress: json['customer_full_address'] as String?,
      customerLat: json['customer_lat'] as String?,
      customerLong: json['customer_long'] as String?,
      customerPostcode: json['customer_postcode'] as String?,
      totalWeight: json['total_weight'] as int?,
      notifyLimitWeight: json['notify_limit_weight'] as String?,
      sellerId: json['seller_id'] as String?,
      sellerCode: json['seller_code'] as String?,
      sellerName: json['seller_name'] as String?,
      notificationDistributor: json['notification_distributor'] as int?,
      shippingError: json['shipping_error'] as String?,
    );

Map<String, dynamic> _$DataCardResponseToJson(DataCardResponse instance) =>
    <String, dynamic>{
      'id': instance.id,
      'user_id': instance.userId,
      'session_id': instance.sessionId,
      'phone': instance.phone,
      'address': instance.address,
      'ship_address_latlong': instance.shipAddressLatlong,
      'shipping_address_id': instance.shippingAddressId,
      'address_window_id': instance.addressWindowId,
      'street_address': instance.streetAddress,
      'shipping_address_full_name': instance.shippingAddressFullName,
      'shipping_address_ward': instance.shippingAddressWard,
      'shipping_address_district': instance.shippingAddressDistrict,
      'shipping_address_city': instance.shippingAddressCity,
      'description': instance.description,
      'payment_method': instance.paymentMethod,
      'payment_method_name': instance.paymentMethodName,
      'shipping_method': instance.shippingMethod,
      'shipping_method_code': instance.shippingMethodCode,
      'shipping_method_name': instance.shippingMethodName,
      'shipping_service': instance.shippingService,
      'is_freeship': instance.isFreeship,
      'shipping_note': instance.shippingNote,
      'shipping_diff': instance.shippingDiff,
      'service_name': instance.serviceName,
      'extra_service': instance.extraService,
      'ship_fee': instance.shipFee,
      'ship_fee_down': instance.shipFeeDown,
      'estimated_deliver_time': instance.estimatedDeliverTime,
      'lading_method': instance.ladingMethod,
      'ship_fee_start': instance.shipFeeStart,
      'receiving_time': instance.receivingTime,
      'total': instance.total,
      'customer_point': instance.customerPoint,
      'customer_exchange_point': instance.customerExchangePoint,
      'total_product_promotion': instance.totalProductPromotion,
      'total_product': instance.totalProduct,
      'total_product_promotion_fortmated':
          instance.totalProductPromotionFortmated,
      'total_product_fortmated': instance.totalProductFortmated,
      'total_fortmated': instance.totalFortmated,
      'total_quantity': instance.totalQuantity,
      'created_at': instance.createdAt,
      'created_by': instance.createdBy,
      'updated_at': instance.updatedAt,
      'updated_by': instance.updatedBy,
      'details': instance.details,
      'total_point': instance.totalPoint,
      'full_name': instance.fullName,
      'email': instance.email,
      'distributor_id': instance.distributorId,
      'distributor_code': instance.distributorCode,
      'distributor_name': instance.distributorName,
      'distributor_phone': instance.distributorPhone,
      'distributor_lat': instance.distributorLat,
      'distributor_long': instance.distributorLong,
      'distributor_postcode': instance.distributorPostcode,
      'order_type': instance.orderType,
      'distributor_city_code': instance.distributorCityCode,
      'distributor_district_code': instance.distributorDistrictCode,
      'distributor_ward_code': instance.distributorWardCode,
      'distributor_city_name': instance.distributorCityName,
      'distributor_district_name': instance.distributorDistrictName,
      'distributor_ward_name': instance.distributorWardName,
      'distributor_full_address': instance.distributorFullAddress,
      'customer_city_code': instance.customerCityCode,
      'customer_district_code': instance.customerDistrictCode,
      'customer_ward_code': instance.customerWardCode,
      'customer_city_name': instance.customerCityName,
      'customer_district_name': instance.customerDistrictName,
      'customer_ward_name': instance.customerWardName,
      'customer_full_address': instance.customerFullAddress,
      'customer_lat': instance.customerLat,
      'customer_long': instance.customerLong,
      'customer_postcode': instance.customerPostcode,
      'total_weight': instance.totalWeight,
      'notify_limit_weight': instance.notifyLimitWeight,
      'seller_id': instance.sellerId,
      'seller_code': instance.sellerCode,
      'seller_name': instance.sellerName,
      'notification_distributor': instance.notificationDistributor,
      'shipping_error': instance.shippingError,
    };

Details _$DetailsFromJson(Map<String, dynamic> json) => Details(
      id: json['id'] as int?,
      cartId: json['cart_id'] as int?,
      productId: json['product_id'] as int?,
      productCode: json['product_code'] as String?,
      productName: json['product_name'] as String?,
      productThumb: json['product_thumb'] as String?,
      quantity: json['quantity'] as int?,
      productUnit: json['product_unit'] as String?,
      productUnitName: json['product_unit_name'] as String?,
      price: json['price'] as int?,
      cartInfo: (json['card_info'] as List<dynamic>?)
          ?.map((e) => CardInfo.fromJson(e as Map<String, dynamic>))
          .toList(),
      cardCode: json['card_code'] as String?,
      priceFormatted: json['price_formatted'] as String?,
      totalPrice: json['total_price'] as int?,
      totalPriceFormatted: json['total_price_formatted'] as String?,
      special: json['special'] as int?,
      specialFormatted: json['special_formatted'] as String?,
      specialPrice: json['special_price'] as int?,
      specialPriceFormatted: json['special_price_formatted'] as String?,
      promotionPrice: json['promotion_price'] as int?,
      promotionPriceFormatted: json['promotion_price_formatted'] as String?,
      totalPromotionPrice: json['total_promotion_price'] as int?,
      totalPromotionPriceFormatted:
          json['total_promotion_price_formatted'] as String?,
      total: json['total'] as int?,
      totalGiftCard: json['total_gift_card'] as int?,
      totalFormatted: json['total_formatted'] as String?,
      note: json['note'] as String?,
      optionDetails: json['option_details'] as String?,
      createdAt: json['created_at'] as String?,
      createdBy: json['created_by'] as String?,
      updatedAt: json['updated_at'] as String?,
      updatedBy: json['updated_by'] as String?,
    );

Map<String, dynamic> _$DetailsToJson(Details instance) => <String, dynamic>{
      'id': instance.id,
      'cart_id': instance.cartId,
      'product_id': instance.productId,
      'product_code': instance.productCode,
      'product_name': instance.productName,
      'product_thumb': instance.productThumb,
      'quantity': instance.quantity,
      'product_unit': instance.productUnit,
      'product_unit_name': instance.productUnitName,
      'price': instance.price,
      'card_info': instance.cartInfo,
      'card_code': instance.cardCode,
      'price_formatted': instance.priceFormatted,
      'total_price': instance.totalPrice,
      'total_price_formatted': instance.totalPriceFormatted,
      'special': instance.special,
      'special_formatted': instance.specialFormatted,
      'special_price': instance.specialPrice,
      'special_price_formatted': instance.specialPriceFormatted,
      'promotion_price': instance.promotionPrice,
      'promotion_price_formatted': instance.promotionPriceFormatted,
      'total_promotion_price': instance.totalPromotionPrice,
      'total_promotion_price_formatted': instance.totalPromotionPriceFormatted,
      'total': instance.total,
      'total_gift_card': instance.totalGiftCard,
      'total_formatted': instance.totalFormatted,
      'note': instance.note,
      'option_details': instance.optionDetails,
      'created_at': instance.createdAt,
      'created_by': instance.createdBy,
      'updated_at': instance.updatedAt,
      'updated_by': instance.updatedBy,
    };
